/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntentTestRouteImport } from './routes/intent-test'
import { Route as IndexRouteImport } from './routes/index'

const IntentTestRoute = IntentTestRouteImport.update({
  id: '/intent-test',
  path: '/intent-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intent-test': typeof IntentTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intent-test': typeof IntentTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intent-test': typeof IntentTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/intent-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/intent-test'
  id: '__root__' | '/' | '/intent-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntentTestRoute: typeof IntentTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intent-test': {
      id: '/intent-test'
      path: '/intent-test'
      fullPath: '/intent-test'
      preLoaderRoute: typeof IntentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntentTestRoute: IntentTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
